---
- hosts: ropsten
  user: ubuntu
  become: yes
  become_method: sudo
  vars:
    geth_testnet: true
    geth_cache: 512
    geth_port: 30304
    geth_datadir: /data/ropsten
    geth_rpc: true
    geth_rpcpublic: true
    geth_rpcaddr: 0.0.0.0
    geth_rpcport: 8080
    geth_rpcapi: "eth,net,web3"
    geth_rpccorsdomain: "*"
  roles:
    - geth-node
